app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('members/', include('members.urls')),
    path('posts/', include('posts.urls')),

]

urlpatterns += static(
    # URL앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root위치에서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_views, name='login'),
]

app/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('<int:pk>/like/', views.post_like, name='post-like'),
]

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    사용자모델로 쓰입니다
    """
    img_profile = models.ImageField('프로필이미지', blank=True, upload_to='userssadf/')

app/posts/models.py
from django.db import models
from members.models import User

class Post(models.Model):
    """
    인스타그램의 포스트
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    like_users = models.ManyToManyField(
        User, through='PostLike', related_name='like_post_set',
    )
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '{author} | {created}'.format(
            author=self.author.username,
            created=self.created,
        )

class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/images')

class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

class PostLike(models.Model):
    """
    사용자가 좋아요 누른 Post정보를 저장
    Many-to-many필드를 중간모델(Intermediate Model)을 거쳐 사용
        언제 생성되었는지를 Extra field로 저장! (created)
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

app/config/views.py
from django.shortcuts import render, redirect


def index(request):
    """
    settings.TEMPLATES의 DIR에
        instagram/app/templates 경로를 추가

    Template: templates/index.html
        <h1>Index!</h1>

    URL:    '/', name='index'

    base.html 추가
        상단에 {% load static %}
        정적파일 불러올 때 {% static '경로' %}로 불러옴

    index.html과 login.html이 base.html을 extends하도록 함
    """
    if request.user.is_authenticated:
        return redirect('posts:post-list')
    return render(request, 'index.html')

app/members/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect


def login_views(request):
    """
    Template: templates/members/login.html
        POST요청을 처리하는 form
        내부에는 input 2개를 가지며, 각각 username, password로 name을 가짐

    URL: /members/login/ (members.urls를 사용, config.urls에 include하여 사용)
        name: members:login (url namespace 사용)

    POST요청시, 예제를 보고 적절히 로그인 처리한 후, index로 돌아갈 수 있도록 한다
    로그인에 실패하면 다시 로그인페이지로 이동
    :param request:
    :return:
    """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print('username:', username)
        print('password:', password)
        user = authenticate(request, username=username, password=password)
        print('user:', user)

        if user:
            login(request, user)
            return redirect('posts:post-list')
        else:
            return redirect('members:login')

    return render(request, 'members/login.html')

app/posts/views.py
from django.shortcuts import render, redirect

from posts.models import Post, PostLike


def post_list(request):
    # 1. 로그인 완료 후 이 페이지로 이동하도록 함
    # 2. index에 접근할 때 로그인이 되어 있다면, 이 페이지로 이동하도록 함
    #    로그인이 되어있는지 확인
    #       request.user.is_authenticated가 True인지 체크
    #
    # URL:  /posts/ (posts.urls를 사용, config.urls에서 include)
    #       app_name: 'posts'
    #       url name: 'post-list'
    #       -> posts:post-list
    # Template: templates/posts/post-list.html
    #       <h1>Post List</h1>

    # 'posts'라는 키로 모든 Post QuerySet을 전달
    # (순서는 pk의 역순)
    # 그리고 전달받은 QuerySet을 순회하며 적절히 Post내용을 출력
    posts = Post.objects.order_by('-pk')
    context = {
        'posts': posts,
    }
    return render(request, 'posts/post-list.html', context)

def post_like(request, pk):
    """
    pk가 pk인 Post와 (변수명 post사용)
    request.user로 전달되는 User (변수명 user사용)에 대해
    1. PostLike(post=post, user=user)인 PostLike객체가 존재하는지 확인한다
    2-1. 만약 해당 객체가 이미 있다면, 삭제한다
    2-2. 만약 해당 객체가 없다면 새로 만든다
    3. 완료 후 posts:post-list로 redirect한다
    URL: /posts/<pk>/like/
    """
    post = Post.objects.get(pk=pk)
    user = request.user
    print('post:', post)
    print('user:', user)

    post_like_qs = PostLike.objects.filter(post=post, user=user)
    # user, post에 해당하는 PostLike가 있는 경우
    if post_like_qs.exists():
        # 삭제
        post_like_qs.delete()
    # 없는 경우
    else:
        # 만든다
        PostLike.objects.create(post=post, user=user)

    return redirect('posts:post-list')

app/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/static/bootstrap/bootstrap.css">
</head>
<body>
    <div id="wrap">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="mr-auto ml-auto mt-3
                    col-lg-4
                    col-md-6
                    col-sm-8
                    col-10">
            <div class="card text-center p-4">

                <div>{{ request.user }}</div>
                <div>{{ request.user.is_authenticated }}</div>

                <h1>Instagram</h1>
                <p class="text-secondary">친구들의 사진과 동영상을 보려면 가입하세요</p>
                <button class="btn btn-primary btn-block">Facebook으로 로그인</button>
                <hr>
                <form action="">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="휴대폰 번호 또는 이메일 주소">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="성명">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="사용자 이름">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="비밀번호">
                    </div>
                    <button class="btn btn-primary btn-block">가입</button>
                </form>
                <p class="text-secondary">가입하면 Instagram의 약관 데이터 정책 및 쿠키 정책에 동의하게 됩니다</p>
            </div>

            <div class="card text-center p-4 mt-3 mb-3">
                <span>계정이 있으신가요?</span>
                <a href="{% url 'members:login' %}">로그인</a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/members/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="mr-auto ml-auto mt-3
                    col-lg-4
                    col-md-6
                    col-sm-8
                    col-10">
            <div class="card text-center p-4">
                <h1>Instagram</h1>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input name="username" type="text" class="form-control" placeholder="휴대폰 번호 또는 이메일 주소">
                    </div>
                    <div class="form-group">
                        <input name="password" type="password" class="form-control" placeholder="비밀번호">
                    </div>
                    <button class="btn btn-primary btn-block">로그인</button>
                </form>
                <hr>
                <button class="btn btn-block btn-outline-primary mb-3">Facebook으로 로그인</button>
                <a href="">비밀번호를 잊으셨나요?</a>
            </div>

            <div class="card text-center p-4 mt-3 mb-3">
                <span>계정이 없으신가요?</span>
                <a href="{% url 'index' %}">가입하기</a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/posts/post-list.html
{% extends 'base.html' %}

{% block content %}
    {% for post in posts %}
        <div>{{ post.author }}</div>
        <div>{{ post.created }}</div>
        <!--
            post_like에 POST요청을 보내는 Form구현
            - input을 갖지 않음
            - csrf_token만 추가 {# {% url %} #}
            - 보내는 곳(action)에, url 태그를 적절히 활용
              ex) /posts/1/like/
                  /posts/2/like/
              Post의 pk에 따라 위와 같은 URL을 동적으로 생성해야 함
        -->
{#        <form action="/posts/{{ post.pk }}/like/" method="POST">#}
        <form action="{% url 'posts:post-like' pk=post.pk %}" method="POST">
            {% csrf_token %}

            <!--
            사용가능한 변수
            - user (User)
            - post (Post)
            Template에서의 메서드 콜
             post.like_users.all() -> post.like_users.all
              호출구문()을 제외해야 합니다
            in operator
            <변수> in <반복가능개체(QuerySet등)>
            -> True/False를 반환
            user와 post.like_users을 적절히 이용해서
            현재 request.user가 이 Post의 like_users에 포함되는지를 검사해서
            아래의 if/else/endif구문이 동작하도록 작성해본다
            user.like_post_set를 이용해서 아래 조건문이 동작하도록 해본다
            -->
            {# {% if user in post.like_users.all %} #}
            {% if post in user.like_post_set.all %}
                <div>좋아요 눌린 상태</div>
            {% else %}
                <div>좋아요 안 눌린 상태</div>
            {% endif %}
            <button type="submit">좋아요</button>
        </form>
        <hr>
    {% endfor %}
{% endblock %}